"""empty message

Revision ID: 29c35e8b3026
Revises: 
Create Date: 2023-11-13 13:32:38.242357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29c35e8b3026'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('userId', sa.String(length=30), nullable=False),
    sa.Column('userName', sa.String(length=20), nullable=False),
    sa.Column('userPwd', sa.String(length=50), nullable=False),
    sa.Column('createTime', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('userId')
    )
    op.create_table('UserFile',
    sa.Column('userId', sa.String(length=20), nullable=False),
    sa.Column('fileId', sa.Integer(), nullable=False),
    sa.Column('FileName', sa.Text(), nullable=False),
    sa.Column('downTimes', sa.Integer(), nullable=False),
    sa.Column('createTime', sa.DateTime(), nullable=False),
    sa.Column('delStatus', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('userId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('UserFile')
    op.drop_table('User')
    # ### end Alembic commands ###
