"""empty message

Revision ID: 80e0e0ab2dcb
Revises: 5b2833245985
Create Date: 2023-11-15 09:18:16.896928

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '80e0e0ab2dcb'
down_revision = '5b2833245985'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('UserFile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('userName', sa.String(length=255), nullable=False))
        batch_op.drop_column('userId')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('UserFile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('userId', mysql.VARCHAR(length=255), nullable=False))
        batch_op.drop_column('userName')

    # ### end Alembic commands ###
