"""empty message

Revision ID: b821f44d7171
Revises: 80e0e0ab2dcb
Create Date: 2023-11-15 09:32:31.667692

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b821f44d7171'
down_revision = '80e0e0ab2dcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('UserFile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fileName', sa.Text(), nullable=False))
        batch_op.drop_column('FileName')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('UserFile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('FileName', mysql.TEXT(), nullable=False))
        batch_op.drop_column('fileName')

    # ### end Alembic commands ###
